<?php
/**
 * @file inc/config/defaultsettings.inc.php
 * @brief Default settings for mapping database records to myExperiment Linked Data.
 * @version beta
 * @author David R Newman
 * @details Default settings for mapping database records to myExperiment Linked Data.
 */


/** @brief A string specifying where the myExperiment Linked Data repository is located on the local system. */
$lddir="/var/linkeddata/";
ini_set('include_path',".:${lddir}inc/:");
/** @brief A string specifying where the files for the web pages of myExperiment Linked Data are located on the local system. */
$httpdir="/var/www/html/linkeddata/";
/** @brief A string specifying the base URI for any myExperiment RDF entities that are generated.  (E.g. http://www.myexperiment.org/). */
$datauri="http://www.myexperiment.org/";
/** @brief A string specifying the base URI for any myExperiment RDF entities referred to in user documentation. */
$guidedatauri="http://www.myexperiment.org/";
/** @brief A string specifying the base URI for any entities that are hosted locally. */
$hostpath=$datauri;
if (isset($_SERVER['SERVER_NAME'])) $hostpath="http://".$_SERVER['SERVER_NAME']."/";
/** @brief A string specifying the base URI for myExperiment ontology modules.  (E.g. http://rdf.myexperiment.org/ontologies/). */
$ontopath="http://rdf.myexperiment.org/ontologies/";
/** @brief A string specifying the path where RDF and other data files generated by myExperiment Linked Data scripts should be stored. */
$datapath="/var/linkeddata/data/";
/** @brief A string specifying where the myExperiment Ruby-on-Rails application resides if it is deployed locally. */
$myexppath="/var/rails/myexperiment/";
/** @brief A string specifying the local filesystem path to 4Store command line interface scripts. */
$store4execpath="/usr/local/bin/";
/** @brief A string specifying the local filesystem path to the PHP command line interface. */
$phppath="/usr/bin/";
/** @brief A string specifying the local filesystem path to the Rake command line interface. */
$rakepath="";
/** @brief A string specifying the name of the myExperiment knowledge base. */
$myexp_kb="myexp_public";
/** @brief A string specifying the name of the ontologies knowledge base. */
$onto_kb="ontologies";
/** @brief An associative array containing the credentials needed to connect to the myExperiment database. */
$myexp_db=array("user"=>"username","password"=>"password","server"=>"localhost","database"=>"dbname");
/** @brief An associative array containing the credentials needed to connect to the ontologies database. */
$onto_db=array("user"=>"username","password"=>"password","server"=>"localhost","database"=>"dbname");
/** @brief An associative array containing the credentials needed to connect to the SPARQL queries database. */
$sparql_db=array("user"=>"username","password"=>"password","server"=>"localhost","database"=>"dbname");
/** @brief A string specifying the version of 4Store, RAPTOR and RASQAL used by the knowledge bases / SPARQL endpoints. */
$store4versions="4Store (undefined), Raptor (undefined), Rasqal (undefined)";
/** @brief A boolean specifying whether rake can be invoked to retrieve data from a Ruby-on-Rail application. (E.g. Get dataflow XML as it would appear from the REST API). */
$use_rake=TRUE;
/** @brief A string specifying the Rails environment under which to run Rake or any other Ruby-on-Rails applications. */
$rails_env="production";
