<?php
/**
 * @file inc/config/defaultsettings_installer.inc.php
 * @brief Default settings used by the installer of myExperiment Linked Data.
 * @version beta
 * @author David R Newman
 * @details Default settings used unchanged by the installer of myExperiment Linked Data, including RDF generation, SPARQL endpoint, ontology, HTML ontology specification generator, etc.
 */

/** @brief A string specifying where the myExperiment Linked Data repository is located on the local system. */
$lddir="THIS_DIR";
ini_set('include_path',".:${lddir}inc/:");
/** @brief A string specifying the path where RDF and other data files generated by myExperiment Linked Data scripts should be stored. */
$datapath="${lddir}data/";
/** @brief A string specifying the base URI for any myExperiment RDF entities that are generated.  (E.g. http://www.myexperiment.org/). */
$datauri="DATAURI";
/** @brief A string specifying the base URI for myExperiment ontology modules.  (E.g. http://rdf.myexperiment.org/ontologies/).
$ontopath="http://rdf.myexperiment.org/ontologies/";
/** @brief A string specifying where the myExperiment Ruby-on-Rails application resides if it is deployed locally. */
$myexppath="MYEXP_PATH";
/** @brief An associative array containing the credentials needed to connect to the myExperiment database. */
$myexp_db=array("user"=>"MYSQL_USERNAME","password"=>"MYSQL_PASSWORD","server"=>"localhost","database"=>"DATABASE");
/** @brief A boolean specifying whether rake can be invoked to retrieve data from a Ruby-on-Rail application. (E.g. Get dataflow XML as it would appear from the REST API). */
$use_rake=TRUE;
