#!/bin/bash
## @file 4store/scripts/createDataFolders.sh
## @brief Creates folders required for storing data generate through querying either the myExperiment or ontologies 4Store knowledge bases.
## @author David R Newman
## @version beta
## @details This script creates folders for storing the HTML specification document of the myExperiment ontology, the linksets for myExperiment Linked Data, the dataflows for public workflows on myExperiment.  It also creates folders for storing local copies of uploaded ontologies/schemas, as well as reasoned versions and HTML specification documents of these ontologies/schemas.  The script also ensures all these folders have appropriate ownership/permissions to allow files generated by other scripts to be deposited.

source `dirname $BASH_SOURCE`/settings.sh
if [ -e $DATA_PATH/$TRIPLESTORE ]; then
	echo "Data folders have already been created!"
else
	cd $DATA_PATH
	mkdir $TRIPLESTORE
	mkdir $TRIPLESTORE/html
        mkdir $TRIPLESTORE/linksets
	mkdir dataflows/
	ln -s $DATA_PATH/dataflows/ $TRIPLESTORE/dataflows
	echo "ln -s $DATA_PATH/dataflows/ $TRIPLESTORE/dataflows"
	mkdir ontologies
	mkdir ontologies/remoteont
	mkdir ontologies/reasoned
	mkdir ontologies/cachedspec
	sudo chgrp -R $HTTPGROUP *
	sudo chmod -R g+w *
fi
